// Word list data for the learning app

export const wordList = [
  // --- Alphabet Fun Category (100-199) ---
  { id: 101, word: 'Ape', image: 'ape.png', category: 'Alphabet Fun' },
  // In wordList.js, after the "Ape" object
  { id: 101.1, letter: 'A', word: 'Apple', image: 'apple.png', category: 'Alphabet Fun' },
  { id: 101.2, letter: 'A', word: 'Ant', image: 'ant.png', category: 'Alphabet Fun' },
  { id: 101.3, letter: 'A', word: 'Alligator', image: 'alligator.png', category: 'Alphabet Fun' },
  { id: 101.4, letter: 'A', word: 'Astronaut', image: 'astronaut.png', category: 'Alphabet Fun' },
  { id: 102, word: 'Bee', image: 'bee.png', category: 'Alphabet Fun' },
  { id: 102.1, letter: 'B', word: 'Ball', image: 'apple.png', category: 'Alphabet Fun' },
  { id: 102.2, letter: 'B', word: 'Bear', image: 'ant.png', category: 'Alphabet Fun' },
  { id: 102.3, letter: 'B', word: 'Bus', image: 'alligator.png', category: 'Alphabet Fun' },
  { id: 102.4, letter: 'B', word: 'Baby', image: 'astronaut.png', category: 'Alphabet Fun' },
  { id: 103, word: 'Circle', image: 'circle.png', category: 'Alphabet Fun' },
  { id: 103.1, letter: 'C', word: 'Cat', image: 'cat.png', category: 'Alphabet Fun' },
  { id: 103.2, letter: 'C', word: 'Car', image: 'car.png', category: 'Alphabet Fun' },
  { id: 103.3, letter: 'C', word: 'Cookie', image: 'cookie.png', category: 'Alphabet Fun' },
  { id: 103.4, letter: 'C', word: 'Cow', image: 'cow.png', category: 'Alphabet Fun' },
  { id: 104, word: 'Deer', image: 'deer.png', category: 'Alphabet Fun' },
  { id: 104.1, letter: 'D', word: 'Dog', image: 'dog.png', category: 'Alphabet Fun' },
  { id: 104.2, letter: 'D', word: 'Duck', image: 'duck.png', category: 'Alphabet Fun' },
  { id: 104.3, letter: 'D', word: 'Door', image: 'door.png', category: 'Alphabet Fun' },
  { id: 104.4, letter: 'D', word: 'Dinosaur', image: 'dinosaur.png', category: 'Alphabet Fun' },
  { id: 105, word: 'Eagle', image: 'eagle.png', category: 'Alphabet Fun' },
  { id: 105.1, letter: 'E', word: 'Egg', image: 'egg.png', category: 'Alphabet Fun' },
  { id: 105.2, letter: 'E', word: 'Elephant', image: 'elephant.png', category: 'Alphabet Fun' },
  { id: 105.3, letter: 'E', word: 'Elbow', image: 'elbow.png', category: 'Alphabet Fun' },
  { id: 105.4, letter: 'E', word: 'Elf', image: 'elf.png', category: 'Alphabet Fun' },
  { id: 106, word: 'Feather', image: 'feather.png', category: 'Alphabet Fun' },
  { id: 106.1, letter: 'F', word: 'Fish', image: 'fish.png', category: 'Alphabet Fun' },
  { id: 106.2, letter: 'F', word: 'Frog', image: 'frog.png', category: 'Alphabet Fun' },
  { id: 106.3, letter: 'F', word: 'Fire', image: 'fire.png', category: 'Alphabet Fun' },
  { id: 106.4, letter: 'F', word: 'Flower', image: 'flower.png', category: 'Alphabet Fun' },
  { id: 107, word: 'Giraffe', image: 'giraffe.png', category: 'Alphabet Fun' },
  { id: 107.1, letter: 'G', word: 'Goat', image: 'goat.png', category: 'Alphabet Fun' },
  { id: 107.2, letter: 'G', word: 'Girl', image: 'girl.png', category: 'Alphabet Fun' },
  { id: 107.3, letter: 'G', word: 'Grapes', image: 'grapes.png', category: 'Alphabet Fun' },
  { id: 107.4, letter: 'G', word: 'Globe', image: 'globegit log --pretty=format:"%h - %an, %ar : %s".png', category: 'Alphabet Fun' },
  { id: 108, word: 'House', image: 'house.png', category: 'Alphabet Fun' },
  { id: 108.1, letter: 'H', word: 'Hat', image: 'hat.png', category: 'Alphabet Fun' },
  { id: 108.2, letter: 'H', word: 'Horse', image: 'horse.png', category: 'Alphabet Fun' },
  { id: 108.3, letter: 'H', word: 'Hand', image: 'hand.png', category: 'Alphabet Fun' },
  { id: 108.4, letter: 'H', word: 'Heart', image: 'heart.png', category: 'Alphabet Fun' },
  { id: 109, word: 'Ice', image: 'ice.png', category: 'Alphabet Fun' },
  { id: 109.1, letter: 'I', word: 'Igloo', image: 'igloo.png', category: 'Alphabet Fun' },
  { id: 109.2, letter: 'I', word: 'Infant', image: 'infant.png', category: 'Alphabet Fun' },
  { id: 109.3, letter: 'I', word: 'Iguana', image: 'iguana.png', category: 'Alphabet Fun' },
  { id: 109.4, letter: 'I', word: 'Island', image: 'island.png', category: 'Alphabet Fun' },
  { id: 110, word: 'Jay', image: 'jay.png', category: 'Alphabet Fun' },
  { id: 110.1, letter: 'J', word: 'Jacket', image: 'jacket.png', category: 'Alphabet Fun' },
  { id: 110.2, letter: 'J', word: 'Jellyfish', image: 'jellyfish.png', category: 'Alphabet Fun' },
  { id: 110.3, letter: 'J', word: 'Jar', image: 'jar.png', category: 'Alphabet Fun' },
  { id: 110.4, letter: 'J', word: 'Jet', image: 'jet.png', category: 'Alphabet Fun' },
  { id: 111, word: 'Key', image: 'key.png', category: 'Alphabet Fun' },
  { id: 111.1, letter: 'K', word: 'Kite', image: 'kite.png', category: 'Alphabet Fun' },
  { id: 111.2, letter: 'K', word: 'King', image: 'king.png', category: 'Alphabet Fun' },
  { id: 111.3, letter: 'K', word: 'Kitten', image: 'kitten.png', category: 'Alphabet Fun' },
  { id: 111.4, letter: 'K', word: 'Koala', image: 'koala.png', category: 'Alphabet Fun' },
  { id: 112, word: 'Leaf', image: 'leaf.png', category: 'Alphabet Fun' },
  { id: 112.1, letter: 'L', word: 'Lion', image: 'lion.png', category: 'Alphabet Fun' },
  { id: 112.2, letter: 'L', word: 'Lamp', image: 'lamp.png', category: 'Alphabet Fun' },
  { id: 112.3, letter: 'L', word: 'Lemon', image: 'lemon.png', category: 'Alphabet Fun' },
  { id: 112.4, letter: 'L', word: 'Lollipop', image: 'lollipop.png', category: 'Alphabet Fun' },
  { id: 113, word: 'Mailbox', image: 'mailbox.png', category: 'Alphabet Fun' },
  { id: 113.1, letter: 'M', word: 'Monkey', image: 'monkey.png', category: 'Alphabet Fun' },
  { id: 113.2, letter: 'M', word: 'Moon', image: 'moon.png', category: 'Alphabet Fun' },
  { id: 113.3, letter: 'M', word: 'Mouse', image: 'mouse.png', category: 'Alphabet Fun' },
  { id: 113.4, letter: 'M', word: 'Mushroom', image: 'mushroom.png', category: 'Alphabet Fun' },
  { id: 114, word: 'Nest', image: 'nest.png', category: 'Alphabet Fun' },
  { id: 114.1, letter: 'N', word: 'Nurse', image: 'nurse.png', category: 'Alphabet Fun' },
  { id: 114.2, letter: 'N', word: 'Net', image: 'net.png', category: 'Alphabet Fun' },
  { id: 114.3, letter: 'N', word: 'Nail', image: 'nail.png', category: 'Alphabet Fun' },
  { id: 114.4, letter: 'N', word: 'Necklace', image: 'necklace.png', category: 'Alphabet Fun' },
  { id: 115, word: 'Ocean', image: 'ocean.png', category: 'Alphabet Fun' },
  { id: 115.1, letter: 'O', word: 'Octopus', image: 'octopus.png', category: 'Alphabet Fun' },
  { id: 115.2, letter: 'O', word: 'Otter', image: 'otter.png', category: 'Alphabet Fun' },
  { id: 115.3, letter: 'O', word: 'Ostrich', image: 'ostrich.png', category: 'Alphabet Fun' },
  { id: 115.4, letter: 'O', word: 'Ox', image: 'ox.png', category: 'Alphabet Fun' },
  { id: 116, word: 'Peanut', image: 'peanut.png', category: 'Alphabet Fun' },
  { id: 116.1, letter: 'P', word: 'Peacock', image: 'peacock.png', category: 'Alphabet Fun' },
  { id: 116.2, letter: 'P', word: 'Pizza', image: 'pizza.png', category: 'Alphabet Fun' },
  { id: 116.3, letter: 'P', word: 'Pencil', image: 'pencil.png', category: 'Alphabet Fun' },
  { id: 116.4, letter: 'P', word: 'Pumpkin', image: 'pumpkin.png', category: 'Alphabet Fun' },
  { id: 117, word: 'Queue', image: 'queue.png', category: 'Alphabet Fun' },
  { id: 117.1, letter: 'Q', word: 'Queen', image: 'queen.png', category: 'Alphabet Fun' },
  { id: 117.2, letter: 'Q', word: 'Quilt', image: 'quilt.png', category: 'Alphabet Fun' },
  { id: 117.3, letter: 'Q', word: 'Quail', image: 'quail.png', category: 'Alphabet Fun' },
  { id: 117.4, letter: 'Q', word: 'Question Mark', image: 'question-mark.png', category: 'Alphabet Fun' },
  { id: 118, word: 'Rabbit', image: 'rabbit.png', category: 'Alphabet Fun' },
  { id: 118.1, letter: 'R', word: 'Rain', image: 'rain.png', category: 'Alphabet Fun' },
  { id: 118.2, letter: 'R', word: 'Rainbow', image: 'rainbow.png', category: 'Alphabet Fun' },
  { id: 118.3, letter: 'R', word: 'Robot', image: 'robot.png', category: 'Alphabet Fun' },
  { id: 118.4, letter: 'R', word: 'Rocket', image: 'rocket.png', category: 'Alphabet Fun' },
  { id: 119, word: 'Snake', image: 'snake.png', category: 'Alphabet Fun' },
  { id: 119.1, letter: 'S', word: 'Sun', image: 'sun.png', category: 'Alphabet Fun' },
  { id: 119.2, letter: 'S', word: 'Shoe', image: 'shoe.png', category: 'Alphabet Fun' },
  { id: 119.3, letter: 'S', word: 'Spoon', image: 'spoon.png', category: 'Alphabet Fun' },
  { id: 119.4, letter: 'S', word: 'Star', image: 'star.png', category: 'Alphabet Fun' },
  { id: 120, word: 'Tea', image: 'tea.png', category: 'Alphabet Fun' },
  { id: 120.1, letter: 'T', word: 'Tree', image: 'tree.png', category: 'Alphabet Fun' },
  { id: 120.2, letter: 'T', word: 'Truck', image: 'truck.png', category: 'Alphabet Fun' },
  { id: 120.3, letter: 'T', word: 'Tiger', image: 'tiger.png', category: 'Alphabet Fun' },
  { id: 120.4, letter: 'T', word: 'Table', image: 'table.png', category: 'Alphabet Fun' },
  { id: 121, word: 'Uniform', image: 'uniform.png', category: 'Alphabet Fun' },
  { id: 121.1, letter: 'U', word: 'Umbrella', image: 'umbrella.png', category: 'Alphabet Fun' },
  { id: 121.2, letter: 'U', word: 'Umpire', image: 'umpire.png', category: 'Alphabet Fun' },
  { id: 121.3, letter: 'U', word: 'Unicorn', image: 'unicorn.png', category: 'Alphabet Fun' },
  { id: 121.4, letter: 'U', word: 'Unicycle', image: 'unicycle.png', category: 'Alphabet Fun' },
  { id: 122, word: 'Van', image: 'van.png', category: 'Alphabet Fun' },
  { id: 122.1, letter: 'V', word: 'Violin', image: 'violin.png', category: 'Alphabet Fun' },
  { id: 122.2, letter: 'V', word: 'Volcano', image: 'volcano.png', category: 'Alphabet Fun' },
  { id: 122.3, letter: 'V', word: 'Vase', image: 'vase.png', category: 'Alphabet Fun' },
  { id: 122.4, letter: 'V', word: 'Vest', image: 'vest.png', category: 'Alphabet Fun' },
  { id: 123, word: 'Window', image: 'window.png', category: 'Alphabet Fun' },
  { id: 123.1, letter: 'W', word: 'Wagon', image: 'wagon.png', category: 'Alphabet Fun' },
  { id: 123.2, letter: 'W', word: 'Watch', image: 'watch.png', category: 'Alphabet Fun' },
  { id: 123.3, letter: 'W', word: 'Whale', image: 'whale.png', category: 'Alphabet Fun' },
  { id: 123.4, letter: 'W', word: 'Wheel', image: 'wheel.png', category: 'Alphabet Fun' },
  { id: 124, word: 'X-ray', image: 'x-ray.png', category: 'Alphabet Fun' },
  { id: 124.1, letter: 'X', word: 'Xylophone', image: 'xylophone.png', category: 'Alphabet Fun' },
  { id: 124.2, letter: 'X', word: 'X-box', image: 'xbox.png', category: 'Alphabet Fun' },
  { id: 124.3, letter: 'X', word: 'X-Pen', image: 'x-pen.png', category: 'Alphabet Fun' },
  { id: 124.4, letter: 'X', word: 'Xerox Machine', image: 'xerox-machine.png', category: 'Alphabet Fun' },
  { id: 125, word: 'Yo-yo', image: 'yo-yo.png', category: 'Alphabet Fun' },
  { id: 125.1, letter: 'Y', word: 'Yak', image: 'yak.png', category: 'Alphabet Fun' },
  { id: 125.2, letter: 'Y', word: 'Yarn', image: 'yarn.png', category: 'Alphabet Fun' },
  { id: 125.3, letter: 'Y', word: 'Yacht', image: 'yacht.png', category: 'Alphabet Fun' },
  { id: 125.4, letter: 'Y', word: 'Yogurt', image: 'yogurt.png', category: 'Alphabet Fun' },
  { id: 126, word: 'Zebra', image: 'zebra.png', category: 'Alphabet Fun' },
  { id: 126.1, letter: 'Z', word: 'Zipper', image: 'zipper.png', category: 'Alphabet Fun' },
  { id: 126.2, letter: 'Z', word: 'Zigzag', image: 'zigzag.png', category: 'Alphabet Fun' },
  { id: 126.6, letter: 'Z', word: 'Zeppelin', image: 'zeppelin.png', category: 'Alphabet Fun' },
  { id: 126.5, letter: 'Z', word: 'Zap', image: 'zap.png', category: 'Alphabet Fun' },

  // --- Parts of the Body Category - HEAD PARTS FIRST ---
  { id: 201, word: 'Head', image: { boy: 'boy-head.png', girl: 'girl-head.png' }, category: 'Parts of the Body' },
  { id: 202, word: 'Hair', image: { boy: 'boy-hair.png', girl: 'girl-hair.png' }, category: 'Parts of the Body' },
  { id: 203, word: 'Eyes', image: { boy: 'boy-eyes.png', girl: 'girl-eyes.png' }, category: 'Parts of the Body' },
  { id: 204, word: 'Nose', image: { boy: 'boy-nose.png', girl: 'girl-nose.png' }, category: 'Parts of the Body' },
  { id: 205, word: 'Ears', image: { boy: 'boy-ears.png', girl: 'girl-ears.png' }, category: 'Parts of the Body' },
  { id: 206, word: 'Lips', image: { boy: 'boy-lips.png', girl: 'girl-lips.png' }, category: 'Parts of the Body' },
  { id: 207, word: 'Chin', image: { boy: 'boy-chin.png', girl: 'girl-chin.png' }, category: 'Parts of the Body' },
  { id: 208, word: 'Neck', image: { boy: 'boy-neck.png', girl: 'girl-neck.png' }, category: 'Parts of the Body' },
  { id: 209, word: 'Mouth', image: { boy: 'boy-mouth.png', girl: 'girl-mouth.png' }, category: 'Parts of the Body' },
  { id: 210, word: 'Teeth', image: { boy: 'boy-teeth.png', girl: 'girl-teeth.png' }, category: 'Parts of the Body' },
  { id: 211, word: 'Tongue', image: { boy: 'boy-tongue.png', girl: 'girl-tongue.png' }, category: 'Parts of the Body' },
  { id: 212, word: 'Cheeks', image: { boy: 'boy-cheeks.png', girl: 'girl-cheeks.png' }, category: 'Parts of the Body' },
  { id: 213, word: 'Dimples', image: { boy: 'boy-dimples.png', girl: 'girl-dimples.png' }, category: 'Parts of the Body' },
  { id: 214, word: 'Forehead', image: { boy: 'boy-forehead.png', girl: 'girl-forehead.png' }, category: 'Parts of the Body' },
  { id: 215, word: 'Eyebrows', image: { boy: 'boy-eyebrows.png', girl: 'girl-eyebrows.png' }, category: 'Parts of the Body' },
  { id: 216, word: 'Eyelashes', image: { boy: 'boy-eyelashes.png', girl: 'girl-eyelashes.png' }, category: 'Parts of the Body' },
  { id: 216.1, word: 'Eyelids', image: { boy: 'boy-eyelids.png', girl: 'girl-eyelids.png' }, category: 'Parts of the Body' },
  { id: 217, word: 'Cleft Chin', image: { boy: 'boy-cleft_chin.png', girl: 'girl-cleft_chin.png' }, category: 'Parts of the Body' },

  // --- Parts of the Body Category - OTHER BODY PARTS ---
  { id: 218, word: 'Shoulders', image: { boy: 'boy-shoulders.png', girl: 'girl-shoulders.png' }, category: 'Parts of the Body' },
  { id: 219, word: 'Arms', image: { boy: 'boy-arms.png', girl: 'girl-arms.png' }, category: 'Parts of the Body' },
  { id: 220, word: 'Elbows', image: { boy: 'boy-elbows.png', girl: 'girl-elbows.png' }, category: 'Parts of the Body' },
  { id: 221, word: 'Hands', image: { boy: 'boy-hands.png', girl: 'girl-hands.png' }, category: 'Parts of the Body' },
  { id: 222, word: 'Fingers', image: { boy: 'boy-fingers.png', girl: 'girl-fingers.png' }, category: 'Parts of the Body' },
  { id: 223, word: 'Nails', image: { boy: 'boy-nails.png', girl: 'girl-nails.png' }, category: 'Parts of the Body' },
  { id: 224, word: 'Palms', image: { boy: 'boy-palms.png', girl: 'girl-palms.png' }, category: 'Parts of the Body' },
  { id: 225, word: 'Body', image: { boy: 'boy-body.png', girl: 'girl-body.png' }, category: 'Parts of the Body' },
  { id: 226, word: 'Chest', image: { boy: 'boy-chest.png', girl: 'girl-chest.png' }, category: 'Parts of the Body' },
  { id: 227, word: 'Stomach', image: { boy: 'boy-stomach.png', girl: 'girl-stomach.png' }, category: 'Parts of the Body' },
  { id: 228, word: 'Hips', image: { boy: 'boy-hips.png', girl: 'girl-hips.png' }, category: 'Parts of the Body' },
  { id: 229, word: 'Belly Button', image: { boy: 'boy-belly_button.png', girl: 'girl-belly_button.png' }, category: 'Parts of the Body' },
  { id: 230, word: 'Feet', image: { boy: 'boy-feet.png', girl: 'girl-feet.png' }, category: 'Parts of the Body' },

  // --- Other Categories ---
  { id: 301, word: 'One', image: 'one.png', category: 'Counting' },
  // ... and so on
];

export const getWordsByCategory = (categoryName) => {
  return wordList.filter(word => word.category === categoryName);
};