// Word list data for the learning app

export const wordList = [
  // --- Alphabet Fun Category (100-199) ---
  { id: 101, word: 'Ape', image: 'ape.png', category: 'Alphabet Fun' },
  // In wordList.js, after the "Ape" object
  { id: 101.1, letter: 'A', word: 'Apple', image: 'apple.png', category: 'Alphabet Fun' },
  { id: 101.2, letter: 'A', word: 'Ant', image: 'ant.png', category: 'Alphabet Fun' },
  { id: 101.3, letter: 'A', word: 'Alligator', image: 'alligator.png', category: 'Alphabet Fun' },
  { id: 101.4, letter: 'A', word: 'Astronaut', image: 'astronaut.png', category: 'Alphabet Fun' },
  { id: 102, word: 'Bee', image: 'bee.png', category: 'Alphabet Fun' },
  { id: 102.1, letter: 'B', word: 'Ball', image: 'apple.png', category: 'Alphabet Fun' },
  { id: 102.2, letter: 'B', word: 'Bear', image: 'ant.png', category: 'Alphabet Fun' },
  { id: 102.3, letter: 'B', word: 'Bus', image: 'alligator.png', category: 'Alphabet Fun' },
  { id: 102.4, letter: 'B', word: 'Baby', image: 'astronaut.png', category: 'Alphabet Fun' },
  { id: 103, word: 'Circle', image: 'circle.png', category: 'Alphabet Fun' },
  { id: 103.1, letter: 'C', word: 'Cat', image: 'cat.png', category: 'Alphabet Fun' },
  { id: 103.2, letter: 'C', word: 'Car', image: 'car.png', category: 'Alphabet Fun' },
  { id: 103.3, letter: 'C', word: 'Cookie', image: 'cookie.png', category: 'Alphabet Fun' },
  { id: 103.4, letter: 'C', word: 'Cow', image: 'cow.png', category: 'Alphabet Fun' },
  { id: 104, word: 'Deer', image: 'deer.png', category: 'Alphabet Fun' },
  { id: 104.1, letter: 'D', word: 'Dog', image: 'dog.png', category: 'Alphabet Fun' },
  { id: 104.2, letter: 'D', word: 'Duck', image: 'duck.png', category: 'Alphabet Fun' },
  { id: 104.3, letter: 'D', word: 'Door', image: 'door.png', category: 'Alphabet Fun' },
  { id: 104.4, letter: 'D', word: 'Dinosaur', image: 'dinosaur.png', category: 'Alphabet Fun' },
  { id: 105, word: 'Eagle', image: 'eagle.png', category: 'Alphabet Fun' },
  { id: 105.1, letter: 'E', word: 'Egg', image: 'egg.png', category: 'Alphabet Fun' },
  { id: 105.2, letter: 'E', word: 'Elephant', image: 'elephant.png', category: 'Alphabet Fun' },
  { id: 105.3, letter: 'E', word: 'Elbow', image: 'elbow.png', category: 'Alphabet Fun' },
  { id: 105.4, letter: 'E', word: 'Elf', image: 'elf.png', category: 'Alphabet Fun' },
  { id: 106, word: 'Feather', image: 'feather.png', category: 'Alphabet Fun' },
  { id: 106.1, letter: 'F', word: 'Fish', image: 'fish.png', category: 'Alphabet Fun' },
  { id: 106.2, letter: 'F', word: 'Frog', image: 'frog.png', category: 'Alphabet Fun' },
  { id: 106.3, letter: 'F', word: 'Fire', image: 'fire.png', category: 'Alphabet Fun' },
  { id: 106.4, letter: 'F', word: 'Flower', image: 'flower.png', category: 'Alphabet Fun' },
  { id: 107, word: 'Giraffe', image: 'giraffe.png', category: 'Alphabet Fun' },
  { id: 107.1, letter: 'G', word: 'Goat', image: 'goat.png', category: 'Alphabet Fun' },
  { id: 107.2, letter: 'G', word: 'Girl', image: 'girl.png', category: 'Alphabet Fun' },
  { id: 107.3, letter: 'G', word: 'Garden', image: 'garden.png', category: 'Alphabet Fun' },
  { id: 107.4, letter: 'G', word: 'Green', image: 'green.png', category: 'Alphabet Fun' },
  { id: 108, word: 'House', image: 'house.png', category: 'Alphabet Fun' },
  { id: 108.1, letter: 'H', word: 'Hat', image: 'hat.png', category: 'Alphabet Fun' },
  { id: 108.2, letter: 'H', word: 'Horse', image: 'horse.png', category: 'Alphabet Fun' },
  { id: 108.3, letter: 'H', word: 'Hand', image: 'hand.png', category: 'Alphabet Fun' },
  { id: 108.4, letter: 'H', word: 'Heart', image: 'heart.png', category: 'Alphabet Fun' },
  { id: 109, word: 'Ice', image: 'ice.png', category: 'Alphabet Fun' },
  { id: 109.1, letter: 'I', word: 'Igloo', image: 'igloo.png', category: 'Alphabet Fun' },
  { id: 109.2, letter: 'I', word: 'Infant', image: 'infant.png', category: 'Alphabet Fun' },
  { id: 109.3, letter: 'I', word: 'Iguana', image: 'iguana.png', category: 'Alphabet Fun' },
  { id: 109.4, letter: 'I', word: 'Island', image: 'island.png', category: 'Alphabet Fun' },
  { id: 110, word: 'Jay', image: 'jay.png', category: 'Alphabet Fun' },
  { id: 110.1, letter: 'J', word: 'Jacket', image: 'jacket.png', category: 'Alphabet Fun' },
  { id: 110.2, letter: 'J', word: 'Jellyfish', image: 'jellyfish.png', category: 'Alphabet Fun' },
  { id: 110.3, letter: 'J', word: 'Jar', image: 'jar.png', category: 'Alphabet Fun' },
  { id: 110.4, letter: 'J', word: 'Jet', image: 'jet.png', category: 'Alphabet Fun' },
  { id: 111, word: 'Key', image: 'key.png', category: 'Alphabet Fun' },
  { id: 111.1, letter: 'K', word: 'Kite', image: 'kite.png', category: 'Alphabet Fun' },
  { id: 111.2, letter: 'K', word: 'King', image: 'king.png', category: 'Alphabet Fun' },
  { id: 111.3, letter: 'K', word: 'Kitten', image: 'kitten.png', category: 'Alphabet Fun' },
  { id: 111.4, letter: 'K', word: 'Koala', image: 'koala.png', category: 'Alphabet Fun' },
  { id: 112, word: 'Leaf', image: 'leaf.png', category: 'Alphabet Fun' },
  { id: 112.1, letter: 'L', word: 'Lion', image: 'lion.png', category: 'Alphabet Fun' },
  { id: 112.2, letter: 'L', word: 'Lamp', image: 'lamp.png', category: 'Alphabet Fun' },
  { id: 112.3, letter: 'L', word: 'Lemon', image: 'lemon.png', category: 'Alphabet Fun' },
  { id: 112.4, letter: 'L', word: 'Lollipop', image: 'lollipop.png', category: 'Alphabet Fun' },
  { id: 113, word: 'Mailbox', image: 'mailbox.png', category: 'Alphabet Fun' },

  { id: 114, word: 'Nest', image: 'nest.png', category: 'Alphabet Fun' },
  { id: 115, word: 'Ocean', image: 'ocean.png', category: 'Alphabet Fun' },
  { id: 116, word: 'Peanut', image: 'peanut.png', category: 'Alphabet Fun' },
  { id: 117, word: 'Queue', image: 'queue.png', category: 'Alphabet Fun' },
  { id: 118, word: 'Rabbit', image: 'rabbit.png', category: 'Alphabet Fun' },
  { id: 119, word: 'Snake', image: 'snake.png', category: 'Alphabet Fun' },
  { id: 120, word: 'Tea', image: 'tea.png', category: 'Alphabet Fun' },
  { id: 121, word: 'Uniform', image: 'uniform.png', category: 'Alphabet Fun' },
  { id: 122, word: 'Van', image: 'van.png', category: 'Alphabet Fun' },
  { id: 123, word: 'Window', image: 'window.png', category: 'Alphabet Fun' },
  { id: 124, word: 'X-ray', image: 'x-ray.png', category: 'Alphabet Fun' },
  { id: 125, word: 'Yo-yo', image: 'yo-yo.png', category: 'Alphabet Fun' },
  { id: 126, word: 'Zebra', image: 'zebra.png', category: 'Alphabet Fun' },

  // --- Parts of the Body Category - HEAD PARTS FIRST ---
  { id: 201, word: 'Head', image: { boy: 'boy-head.png', girl: 'girl-head.png' }, category: 'Parts of the Body' },
  { id: 202, word: 'Hair', image: { boy: 'boy-hair.png', girl: 'girl-hair.png' }, category: 'Parts of the Body' },
  { id: 203, word: 'Eyes', image: { boy: 'boy-eyes.png', girl: 'girl-eyes.png' }, category: 'Parts of the Body' },
  { id: 204, word: 'Nose', image: { boy: 'boy-nose.png', girl: 'girl-nose.png' }, category: 'Parts of the Body' },
  { id: 205, word: 'Ears', image: { boy: 'boy-ears.png', girl: 'girl-ears.png' }, category: 'Parts of the Body' },
  { id: 206, word: 'Lips', image: { boy: 'boy-lips.png', girl: 'girl-lips.png' }, category: 'Parts of the Body' },
  { id: 207, word: 'Chin', image: { boy: 'boy-chin.png', girl: 'girl-chin.png' }, category: 'Parts of the Body' },
  { id: 208, word: 'Neck', image: { boy: 'boy-neck.png', girl: 'girl-neck.png' }, category: 'Parts of the Body' },
  { id: 209, word: 'Mouth', image: { boy: 'boy-mouth.png', girl: 'girl-mouth.png' }, category: 'Parts of the Body' },
  { id: 210, word: 'Teeth', image: { boy: 'boy-teeth.png', girl: 'girl-teeth.png' }, category: 'Parts of the Body' },
  { id: 211, word: 'Tongue', image: { boy: 'boy-tongue.png', girl: 'girl-tongue.png' }, category: 'Parts of the Body' },
  { id: 212, word: 'Cheeks', image: { boy: 'boy-cheeks.png', girl: 'girl-cheeks.png' }, category: 'Parts of the Body' },
  { id: 213, word: 'Dimples', image: { boy: 'boy-dimples.png', girl: 'girl-dimples.png' }, category: 'Parts of the Body' },
  { id: 214, word: 'Forehead', image: { boy: 'boy-forehead.png', girl: 'girl-forehead.png' }, category: 'Parts of the Body' },
  { id: 215, word: 'Eyebrows', image: { boy: 'boy-eyebrows.png', girl: 'girl-eyebrows.png' }, category: 'Parts of the Body' },
  { id: 216, word: 'Eyelashes', image: { boy: 'boy-eyelashes.png', girl: 'girl-eyelashes.png' }, category: 'Parts of the Body' },
  { id: 216.1, word: 'Eyelids', image: { boy: 'boy-eyelids.png', girl: 'girl-eyelids.png' }, category: 'Parts of the Body' },
  { id: 217, word: 'Cleft Chin', image: { boy: 'boy-cleft_chin.png', girl: 'girl-cleft_chin.png' }, category: 'Parts of the Body' },

  // --- Parts of the Body Category - OTHER BODY PARTS ---
  { id: 218, word: 'Shoulders', image: { boy: 'boy-shoulders.png', girl: 'girl-shoulders.png' }, category: 'Parts of the Body' },
  { id: 219, word: 'Arms', image: { boy: 'boy-arms.png', girl: 'girl-arms.png' }, category: 'Parts of the Body' },
  { id: 220, word: 'Elbows', image: { boy: 'boy-elbows.png', girl: 'girl-elbows.png' }, category: 'Parts of the Body' },
  { id: 221, word: 'Hands', image: { boy: 'boy-hands.png', girl: 'girl-hands.png' }, category: 'Parts of the Body' },
  { id: 222, word: 'Fingers', image: { boy: 'boy-fingers.png', girl: 'girl-fingers.png' }, category: 'Parts of the Body' },
  { id: 223, word: 'Nails', image: { boy: 'boy-nails.png', girl: 'girl-nails.png' }, category: 'Parts of the Body' },
  { id: 224, word: 'Palms', image: { boy: 'boy-palms.png', girl: 'girl-palms.png' }, category: 'Parts of the Body' },
  { id: 225, word: 'Body', image: { boy: 'boy-body.png', girl: 'girl-body.png' }, category: 'Parts of the Body' },
  { id: 226, word: 'Chest', image: { boy: 'boy-chest.png', girl: 'girl-chest.png' }, category: 'Parts of the Body' },
  { id: 227, word: 'Stomach', image: { boy: 'boy-stomach.png', girl: 'girl-stomach.png' }, category: 'Parts of the Body' },
  { id: 228, word: 'Hips', image: { boy: 'boy-hips.png', girl: 'girl-hips.png' }, category: 'Parts of the Body' },
  { id: 229, word: 'Belly Button', image: { boy: 'boy-belly_button.png', girl: 'girl-belly_button.png' }, category: 'Parts of the Body' },
  { id: 230, word: 'Feet', image: { boy: 'boy-feet.png', girl: 'girl-feet.png' }, category: 'Parts of the Body' },

  // --- Other Categories ---
  { id: 301, word: 'One', image: 'one.png', category: 'Counting' },
  // ... and so on
];

export const getWordsByCategory = (categoryName) => {
  return wordList.filter(word => word.category === categoryName);
};